name: ApiContatosWorkflow

on: 

  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo oi, bem vindo!
